# Generated by Django 4.0.4 on 2022-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_superadmin_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, default='General Office', max_length=50, null=True),
        ),
    ]
