# Generated by Django 4.0.4 on 2022-05-17 17:36

from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('general', 'General'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('service shop', 'Service Shop')], max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
                ('date_joined', models.DateField()),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('first_name'), '-date_joined'],
            },
        ),
    ]
