# Generated by Django 4.0.4 on 2022-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('general office', 'General Office'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('service shop', 'Service Shop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(blank=True, default=None),
        ),
    ]
