# Generated by Django 4.0.4 on 2022-05-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_date_joined_alter_staff_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('General Office', 'General Office'), ('Branch', 'Branch'), ('Warehouse', 'Warehouse'), ('Service Shop', 'Service Shop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(choices=[('WASSCE', 'WASSCE'), ('Diploma', 'Diploma'), ('HND', 'HND'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('hr', 'hr'), ('sales executive', 'Sales Executive'), ('credit officer', 'Credit Officer')], max_length=50),
        ),
    ]
