# Generated by Django 4.0.4 on 2022-05-17 17:36

from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('location', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('location', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
    ]
