# Generated by Django 4.0.4 on 2022-06-04 23:14

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
