# Generated by Django 4.0.4 on 2022-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_model_corporate_sale_price_and_more'),
        ('units', '0002_serviceshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='spare_parts_damaged',
            field=models.ManyToManyField(blank=True, related_name='branch_spare_parts_damaged', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='branch',
            name='spare_parts_in_stock',
            field=models.ManyToManyField(blank=True, related_name='branch_spare_parts_in_stock', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='branch',
            name='spare_parts_missing',
            field=models.ManyToManyField(blank=True, related_name='branch_spare_parts_missing', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vehicles_damaged',
            field=models.ManyToManyField(blank=True, related_name='branch_vehicles_damaged', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vehicles_in_stock',
            field=models.ManyToManyField(blank=True, related_name='branch_vehicles_in_stock', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vehicles_missing',
            field=models.ManyToManyField(blank=True, related_name='branch_vehicles_missing', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='spare_parts_damaged',
            field=models.ManyToManyField(blank=True, related_name='service_shop_spare_parts_damaged', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='spare_parts_in_stock',
            field=models.ManyToManyField(blank=True, related_name='service_shop_spare_parts_in_stock', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='spare_parts_missing',
            field=models.ManyToManyField(blank=True, related_name='service_shop_spare_parts_missing', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='vehicles_damaged',
            field=models.ManyToManyField(blank=True, related_name='service_shop_vehicles_damaged', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='vehicles_in_stock',
            field=models.ManyToManyField(blank=True, related_name='service_shop_vehicles_in_stock', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='vehicles_missing',
            field=models.ManyToManyField(blank=True, related_name='service_shop_vehicles_missing', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='spare_parts_damaged',
            field=models.ManyToManyField(blank=True, related_name='warehouse_spare_parts_damaged', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='spare_parts_in_stock',
            field=models.ManyToManyField(blank=True, related_name='warehouse_spare_parts_in_stock', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='spare_parts_missing',
            field=models.ManyToManyField(blank=True, related_name='warehouse_spare_parts_missing', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='vehicles_damaged',
            field=models.ManyToManyField(blank=True, related_name='warehouse_vehicles_damaged', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='vehicles_in_stock',
            field=models.ManyToManyField(blank=True, related_name='warehouse_vehicles_in_stock', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='vehicles_missing',
            field=models.ManyToManyField(blank=True, related_name='warehouse_vehicles_missing', to='vehicles.vehicle'),
        ),
    ]
