# Generated by Django 4.0.4 on 2022-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(choices=[('at sea', 'At Sea'), ('warehouse', 'Warehouse'), ('branch', 'Branch'), ('service shop', 'Service Shop'), ('finance sale', 'Finance Sale'), ('corporate sale', 'Corporate Sale'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('missing', 'Missing')], default='at sea', max_length=20),
        ),
    ]
