# Generated by Django 4.0.4 on 2022-05-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='spareparttype',
            name='tax',
        ),
    ]
