# Generated by Django 4.0.4 on 2022-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='corporate_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='finance_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='purchase_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='retail_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='wholesale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='corporate_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='finance_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='purchase_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='retail_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='wholesale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
