# Generated by Django 4.0.4 on 2022-05-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_model_corporate_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='corporate_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='finance_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='purchase_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='retail_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='wholesale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='corporate_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='finance_sale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='retail_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wholesale_price',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
