# Generated by Django 4.0.4 on 2022-05-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='on_the_move',
            field=models.BooleanField(default=False),
        ),
    ]
