# Generated by Django 4.0.4 on 2022-06-16 00:19

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchVehiclesSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('supply_code', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=7, max_length=10, prefix='BVS', unique=True)),
                ('vehicles_supplied_quantity', models.CharField(blank=True, max_length=10)),
                ('vehicles_supplied_received', models.CharField(blank=True, default=0, max_length=10)),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_branches', to='units.warehouse')),
                ('vehicles_supplied', models.ManyToManyField(blank=True, related_name='branch_vehicles_supplied', to='vehicles.vehicle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_vehicles', to='operations.container')),
            ],
        ),
    ]
