# Generated by Django 4.0.4 on 2022-06-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_shipment_on_the_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
