# Generated by Django 4.0.4 on 2022-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_model_corporate_sale_price_and_more'),
        ('operations', '0002_serviceshopoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoperation',
            name='spare_parts_missing',
            field=models.ManyToManyField(blank=True, related_name='branch_spare_parts_missing', to='vehicles.sparepart'),
        ),
        migrations.AddField(
            model_name='branchoperation',
            name='vehicles_missing',
            field=models.ManyToManyField(blank=True, related_name='branch_vehicles_missing', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='branchoperation',
            name='spare_parts_damaged',
            field=models.ManyToManyField(blank=True, related_name='branch_spare_parts_damaged', to='vehicles.sparepart'),
        ),
        migrations.AlterField(
            model_name='branchoperation',
            name='vehicles_damaged',
            field=models.ManyToManyField(blank=True, related_name='branch_vehicles_damaged', to='vehicles.vehicle'),
        ),
    ]
