# Generated by Django 4.0.4 on 2022-06-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_branchvehiclessupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchvehiclessupply',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_vehicles_for_supply', to='operations.container'),
        ),
    ]
