# Generated by Django 4.0.4 on 2022-05-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_branchoperation_spare_parts_missing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='service_shop',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='spare_parts_damaged',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='spare_parts_in_stock',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='spare_parts_missing',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='vehicles_damaged',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='vehicles_in_stock',
        ),
        migrations.RemoveField(
            model_name='serviceshopoperation',
            name='vehicles_missing',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='spare_parts_damaged',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='spare_parts_in_stock',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='spare_parts_missing',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='vehicles_damaged',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='vehicles_in_stock',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='vehicles_missing',
        ),
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='BranchOperation',
        ),
        migrations.DeleteModel(
            name='ServiceShopOperation',
        ),
        migrations.DeleteModel(
            name='WarehouseOperation',
        ),
    ]
