# Generated by Django 4.0.4 on 2022-06-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_shipment_departed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='departed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
