# Generated by Django 4.0.4 on 2022-06-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('operations', '0003_alter_branchvehiclessupply_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchvehiclessupply',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_branches', to='units.branch'),
        ),
        migrations.AlterField(
            model_name='branchvehiclessupply',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_vehicles_for_supply', to='units.warehouse'),
        ),
    ]
