# Generated by Django 4.0.4 on 2022-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_shipment_departed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
