# Generated by Django 4.0.4 on 2022-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_current_location'),
        ('operations', '0004_alter_branchvehiclessupply_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSparePartsSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('supply_code', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=7, max_length=10, prefix='BPS', unique=True)),
                ('spare_parts_supplied_quantity', models.CharField(blank=True, max_length=10)),
                ('spare_parts_supplied_received', models.CharField(blank=True, default=0, max_length=10)),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_branches', to='units.branch')),
                ('spare_parts_supplied', models.ManyToManyField(blank=True, related_name='branch_vehicles_supplied', to='vehicles.sparepart')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_spare_part_for_supply', to='units.warehouse')),
            ],
        ),
    ]
