# Generated by Django 4.0.4 on 2022-05-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_serviceshopoperation_service_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoice',
            name='document',
            field=models.FileField(upload_to='invoices/commercial'),
        ),
        migrations.AlterField(
            model_name='commercialinvoice',
            name='invoice_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='invoice_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
