# Generated by Django 4.0.4 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_shipment_departed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
