# Generated by Django 4.0.4 on 2022-06-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_branchsparepartssupply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchsparepartssupply',
            options={'ordering': ['-supply_date']},
        ),
        migrations.AlterModelOptions(
            name='branchvehiclessupply',
            options={'ordering': ['-supply_date']},
        ),
        migrations.AlterModelOptions(
            name='warehousesparepartssupply',
            options={'ordering': ['-supply_date']},
        ),
        migrations.AlterModelOptions(
            name='warehousevehiclessupply',
            options={'ordering': ['-supply_date']},
        ),
    ]
