# Generated by Django 4.0.4 on 2022-07-08 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default=None, max_length=50, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('consumption_type', models.CharField(blank=True, choices=[('finance sale', 'Finance Sale'), ('corporate sale', 'Corporate Sale')], default=None, max_length=50, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('invoice_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=7, max_length=10, prefix='STL', unique=True)),
                ('discount', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('tax', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_customers', to='sales.customer')),
                ('spare_parts_sold', models.ManyToManyField(blank=True, related_name='wholesale_spare_part_sales', to='vehicles.sparepart')),
                ('vehicles_sold', models.ManyToManyField(blank=True, related_name='wholesale_vehicle_sales', to='vehicles.vehicle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_sales', to='units.warehouse')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('invoice_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=7, max_length=10, prefix='STL', unique=True)),
                ('discount', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('tax', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_sales', to='units.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_customers', to='sales.customer')),
                ('spare_parts_sold', models.ManyToManyField(blank=True, related_name='retail_spare_part_sales', to='vehicles.sparepart')),
                ('vehicles_sold', models.ManyToManyField(blank=True, related_name='retail_vehicle_sales', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAndCorporateSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('invoice_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=7, max_length=10, prefix='STL', unique=True)),
                ('sale_type', models.CharField(blank=True, choices=[('finance sale', 'Finance Sale'), ('corporate sale', 'Corporate Sale')], max_length=50, null=True)),
                ('discount', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('tax', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_customers', to='sales.organization')),
                ('spare_parts_sold', models.ManyToManyField(blank=True, related_name='finance_and_corporate_spare_part_sales', to='vehicles.sparepart')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.warehouse')),
                ('vehicles_sold', models.ManyToManyField(blank=True, related_name='finance_and_corporate_vehicle_sales', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
    ]
