# Generated by Django 4.0.4 on 2022-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeandcorporatesale',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='financeandcorporatesale',
            name='tax',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='retail',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='retail',
            name='tax',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='tax',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
