# Generated by Django 4.0.4 on 2022-06-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('sales', '0003_financeandcorporatesale_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeandcorporatesale',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.organization'),
        ),
        migrations.AlterField(
            model_name='financeandcorporatesale',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.warehouse'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_sales', to='units.branch'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_sales', to='units.warehouse'),
        ),
    ]
