# Generated by Django 4.0.4 on 2022-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_sparepart_current_location_and_more'),
        ('sales', '0004_alter_financeandcorporatesale_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail',
            name='spare_parts_sold',
            field=models.ManyToManyField(blank=True, related_name='retail_spare_part_sales', to='vehicles.sparepart'),
        ),
    ]
