# Generated by Django 4.0.4 on 2022-07-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_retail_spare_parts_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeandcorporatesale',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_customers', to='sales.organization'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_customers', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_customers', to='sales.customer'),
        ),
    ]
